server:
  port: 8080
  servlet:
    context-path: /

spring:
  security:
    oauth2:
      client:
        registration:
          spotify:
            client-id: ${SPOTIFY_CLIENT_ID}
            client-secret: ${SPOTIFY_CLIENT_SECRET}
            scope: user-read-private, user-read-email, playlist-read-private, playlist-modify-public, playlist-modify-private, user-read-playback-state, user-modify-playback-state
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Spotify
            authorization-grant-type: authorization_code
        provider:
          spotify:
            authorization-uri: https://accounts.spotify.com/authorize
            token-uri: https://accounts.spotify.com/api/token
            user-info-uri: https://api.spotify.com/v1/me
            user-name-attribute: id
